imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: services.yml }
    - { resource: "@UtilBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# http://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.root_dir%/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id: ~
    fragments: ~
    http_method_override: true

    
# Assetic Configuration
assetic:
    debug:          "%kernel.debug%"
    use_controller: false
    bundles:        [  ]

    filters:
        cssrewrite: ~
    assets:
        semantic_css:
            inputs:
                - %kernel.root_dir%/../vendor/semantic/ui/dist/semantic.min.css

        semantic_js:
            inputs:
                - %kernel.root_dir%/../vendor/semantic/ui/dist/semantic.min.js

        semantic_icon_woff:
            inputs:
                - %kernel.root_dir%/../vendor/semantic/ui/dist/themes/default/assets/fonts/icons.woff
            output: "css/themes/default/assets/fonts/icons.woff"
        semantic_icon_woff2:
            inputs:
                - %kernel.root_dir%/../vendor/semantic/ui/dist/themes/default/assets/fonts/icons.woff2
            output: "css/themes/default/assets/fonts/icons.woff2"
        semantic_icon_eot:
            inputs:
                - %kernel.root_dir%/../vendor/semantic/ui/dist/themes/default/assets/fonts/icons.eot
            output: "css/themes/default/assets/fonts/icons.eot"
        semantic_icon_otf:
            inputs:
                - %kernel.root_dir%/../vendor/semantic/ui/dist/themes/default/assets/fonts/icons.otf
            output: "css/themes/default/assets/fonts/icons.otf"
        semantic_icon_svg:
            inputs:
                - %kernel.root_dir%/../vendor/semantic/ui/dist/themes/default/assets/fonts/icons.svg
            output: "css/themes/default/assets/fonts/icons.svg"
        semantic_icon_ttf:
            inputs:
                - %kernel.root_dir%/../vendor/semantic/ui/dist/themes/default/assets/fonts/icons.ttf
            output: "css/themes/default/assets/fonts/icons.ttf"

        jquery:
            inputs:
                - %kernel.root_dir%/../vendor/components/jquery/jquery.min.js

        dataTables_css:
            inputs:
                - %kernel.root_dir%/../vendor/datatables/datatables/media/css/dataTables.semanticui.min.css

        dataTable_semantic_js:
            inputs:
                - %kernel.root_dir%/../vendor/datatables/datatables/media/js/dataTables.semanticui.min.js

        jquery_dataTable_js:
              inputs:
                 - %kernel.root_dir%/../vendor/datatables/datatables/media/js/jquery.dataTables.min.js

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_pgsql
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.root_dir%/data/data.db3'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }
