util:
    resource: "@UtilBundle/Controller/"
    type:     annotation
    prefix:   /util

operaciones:
    resource: "@OperacionesBundle/Controller/"
    type:     annotation
    prefix:   /

administrador:
    resource: "@AdministradorBundle/Controller/"
    type:     annotation
    prefix:   /admin

dao:
    resource: "@DaoBundle/Controller/"
    type:     annotation
    prefix:   /dao
