<?php

namespace BD\DaoBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CamarasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CamarasRepository extends EntityRepository
{
  /**
     * Retorna el resultado de la consulta
     *
     * @param boolean $activo
     */
    public function getCamarasQueryBuilder($activo=true) {

        $qb = $this->createQueryBuilder('cam')
                        ->select('cam');
        if($activo){
            $qb->andWhere('cam.activo=:activo')
            ->setParameter('activo', true);
        }

        $qb->orderBy('cam.codigo', 'ASC');

            return $qb;

    }
}
