<?php

namespace BD\DaoBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * CatalogoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CatalogoRepository extends EntityRepository
{

  /**
     * Retorna el resultado de la consulta
     *
     * @param integer $catalogo_id
     */
    public function getCatalogoByIdQueryBuilder($catalogo_id, $activo=true) {


        $qb = $this->createQueryBuilder('cat')
                        ->select('cat')
                        ->Where('cat.catalogo_id=:catalogo_id');
        if($activo){
            $qb->andWhere('cat.activo=:activo')
            ->setParameter('activo', true);
        }

        $qb ->setParameter('catalogo_id', $catalogo_id)
            ->orderBy('cat.orden,cat.nombre', 'ASC');

            return $qb;

    }
}
