<?php

namespace BD\DaoBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ClienteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClienteRepository extends EntityRepository
{
  /**
     * Retorna el resultado de la consulta
     *
     * @param boolean activo
     */
    public function getClientesQueryBuilder($activo=true) {


        $qb = $this->createQueryBuilder('cli')
                        ->select('cli');
        if($activo){
            $qb->andWhere('cli.activo=:activo')
            ->setParameter('activo', true);
        }

        $qb->orderBy('cli.nombre', 'ASC');

            return $qb;

    }
}
