<?php

namespace BD\DaoBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * EmpresaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmpresaRepository extends EntityRepository
{
  /**
     * Retorna el resultado de la consulta
     *
     * @param boolean $activo
     */
    public function getEmpresasQueryBuilder($activo=true) {


        $qb = $this->createQueryBuilder('emp')
                        ->select('emp');
        if($activo){
            $qb->andWhere('emp.activo=:activo')
            ->setParameter('activo', true);
        }

        $qb->orderBy('emp.nombre', 'ASC');

            return $qb;

    }
}
