<?php

namespace BD\DaoBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PuertasRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PuertasRepository extends EntityRepository
{
  /**
     * Retorna el resultado de la consulta
     *
     * @param boolean $activo
     */
    public function getPuertasQueryBuilder($activo=true) {

        $qb = $this->createQueryBuilder('puerta')
                        ->select('puerta');
        if($activo){
            $qb->andWhere('puerta.activo=:activo')
            ->setParameter('activo', true);
        }

        $qb->orderBy('puerta.codigo', 'ASC');

            return $qb;

    }
}
