<?php

namespace BD\DaoBundle\Entity\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * TecnicoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TecnicoRepository extends EntityRepository
{
  /**
     * Retorna el resultado de la consulta
     *
     * @param boolean $activo
     */
    public function getTecnicosQueryBuilder($activo=true) {


        $qb = $this->createQueryBuilder('tec')
                        ->select('tec');
        if($activo){
            $qb->andWhere('tec.activo=:activo')
            ->setParameter('activo', true);
        }

        $qb->orderBy('tec.nombres', 'ASC');

            return $qb;

    }
}
